//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace hr_depart_entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Eployees
    {
        public int Id { get; set; }
        public string fname { get; set; }
        public string mnane { get; set; }
        public string sname { get; set; }
        public System.DateTime bdate { get; set; }
        public int pos_id { get; set; }
        public string order1 { get; set; }
        public string order2 { get; set; }
        public byte[] foto { get; set; }
    }
}
